# Generated by Django 4.0.3 on 2022-03-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
