# Generated by Django 4.0.3 on 2022-03-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='movies',
            new_name='movie',
        ),
    ]
