# Generated by Django 4.0.3 on 2022-03-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_movies_actor_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='movie',
            new_name='movies',
        ),
    ]
